main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.home, name='home'),
     path('about/', views.about, name='about'),

     # INTEREST URLS
     path('interests/', views.InterestList.as_view(), name='interest_list'),
     # path('mygroup/', views.MygroupList.as_view(), name='mygroup_list'),
     path('mygroup/', views.mygroup_index, name='mygroup_index'),
     path('interests/create/', views.InterestCreate.as_view(), name='interest_create'),
     path('interests/<int:pk>/update/', views.InterestUpdate.as_view(), name='interest_update'),
     path('interests/<int:pk>/delete/', views.InterestDelete.as_view(), name='interest_delete'),

     # GROUP URLS
     path('interests/<int:interest_id>/groups/', views.group_list, name='group_list'),
     path('interests/<int:interest_id>/groups/new/', views.group_new, name='group_new'),
     path('interests/<int:interest_id>/groups/create/', views.group_create, name='group_create'),
     path('interests/groups/<int:group_id>/', views.group_detail, name='group_detail'),
     path('interests/groups/<int:pk>/update/', views.GroupUpdate.as_view(), name='group_update'),
     path('interests/groups/<int:pk>/delete/', views.GroupDelete.as_view(), name='group_delete'),
     path('interests/<int:interest_id>/groups/<int:group_id>/add_member/', views.add_member_to_group, name='add_member_to_group'),

     # TOPIC URLS
     path('interests/groups/<int:group_id>/topics', views.topic_create, name='topic_create'),
     path('interests/groups/topics/<int:topic_id>/', views.topic_detail, name='topic_detail'),
     path('interest/groups/topic/<int:pk>/delete/', views.TopicDelete.as_view(), name='topic_delete'),
     path('interest/groups/topic/<int:pk>/update/', views.TopicUpdate.as_view(), name='topic_update'),

     # POST URLS
     path('interest/groups/<int:group_id>/topic/<int:topic_id>/create', views.post_create, name='post_create'),
     path('interest/groups/topic/post/<int:pk>/update/', views.PostUpdate.as_view(), name='post_update'),
     path('interest/groups/topic/post/<int:pk>/delete', views.PostDelete.as_view(), name='post_delete'),
     path('group/<int:group_id>/post/<int:post_id>/like', views.create_like, name="create_like"),
     path('accounts/signup/', views.signup, name='signup'),
]

summit/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime
from django.utils import timezone
from datetime import date
import datetime

# Create your models here.
class Interest(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    createdAt = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-createdAt']
    def __str__(self):
        return f"{self.name}:{self.id}"

    def get_absolute_url(self):
        return reverse('interest_list')


class Group(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image_url = models.CharField(max_length=200)
    createdAt = models.DateTimeField(auto_now_add=True)
    # member = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-createdAt']
    def __str__(self):
        return f"{self.name}:{self.id}"
    def get_absolute_url(self):
        group = Group.objects.get(id=self.id)
        return reverse('group_list', kwargs={'interest_id': group.interest_id})


class Topic(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    name = models.CharField('Topic', max_length=100)
    createdAt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-createdAt']
    
    def __str__(self):
        return f"{self.name}:{self.id}"
    
    def get_absolute_url(self):
        print(self,"-------")
        topic = Topic.objects.get(id=self.id)
        group = topic.group_id
        return reverse('group_detail', kwargs={'group_id':group})


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    image_url = models.CharField(max_length=200)
    createdAt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-createdAt']

    def get_absolute_url(self):
        post = Post.objects.get(id=self.id)
        group = post.topic.group_id
        return reverse('group_detail', kwargs={'group_id': group})


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)


class Member(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    group= models.ForeignKey(Group, on_delete=models.CASCADE)
    interest = models.ForeignKey(Interest, on_delete=models.CASCADE)

main_app/forms.py
from django.forms import ModelForm
from .models import Group, Topic, Post


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['name']

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['content']

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Interest, Topic, Group, Like, Member
from .forms import GroupForm, TopicForm, PostForm
from datetime import datetime
from django.urls import reverse_lazy
from random import randrange
# Create your views here.


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

class InterestList(LoginRequiredMixin, ListView):
    model = Interest
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = Group.objects.all()
        my_group = Member.objects.filter(user_id = self.request.user.id)
        # Add extra context data
        context['user_id'] = self.request.user.id
        context['groups'] = Group.objects.filter(owner_id = self.request.user.id)
        context['my_groups'] = my_group        
        return context

class InterestCreate(LoginRequiredMixin, CreateView):
    model = Interest
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class InterestUpdate(LoginRequiredMixin, UpdateView):
    model = Interest
    fields = ['name']

class InterestDelete(LoginRequiredMixin, DeleteView):
    model = Interest
    success_url = '/interests'

@login_required
def group_list(request, interest_id):
    groups = Group.objects.filter(interest=interest_id)
    interests = Interest.objects.all()
    currentInterest = Interest.objects.get(id=interest_id)
    user_id = request.user.id
    members = Member.objects.all().filter(user_id=user_id)
    return render(request, 'main_app/group_list.html', {
        'interest_id': interest_id,
        'groups': groups,
        'interests': interests,
        'currentInterest': currentInterest,
        'user_id': user_id,
        'members': members,
    })

@login_required
def group_detail(request, group_id):
    group = Group.objects.get(id=group_id)
    topic_form = TopicForm()
    post_form = PostForm()
    topics = group.topic_set.all()
    user_id = request.user.id

    def user_like_post(self):
        return self.like_set.get(user_id = self.user.id)

    return render(request, 'main_app/group_detail.html', {
        'group': group,
        'topic_form': topic_form,
        'topics': topics,
        'post_form': post_form,
        'user_id': user_id
    })

@login_required
def group_new(request, interest_id):
    group_form = GroupForm()
    return render(request, 'main_app/group_new.html', {
        'group_form': group_form,
        'interest_id': interest_id
    })

@login_required
def group_create(request, interest_id):
    random_image = ["icon.svg","initials.svg","laurent.svg","laurent-round.svg","minidenticons.svg"]
    form = GroupForm(request.POST)
    if form.is_valid():
        new_group = form.save(commit=False)
        new_group.interest_id = interest_id
        new_group.owner = request.user
        photo_file = request.FILES.get('photo-file', None)
        if photo_file:
            s3 = boto3.client('s3')
            # need a unique "key" for S3 / needs image file extension too
            key = uuid.uuid4().hex[:6] + \
                photo_file.name[photo_file.name.rfind('.'):]
            # just in case something goes wrong
            try:
                bucket = os.environ['S3_BUCKET']
                s3.upload_fileobj(photo_file, bucket, key)
                # build the full url string
                url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                # we can assign to cat_id or cat (if you have a cat object)
                new_group.image_url = url
            except Exception as e:
                print('An error occurred uploading file to S3')
                print(e)
        if not new_group.image_url:
            new_group.image_url = random_image[randrange(5)]
        new_group.save()
    return redirect('group_list', interest_id=interest_id)

@login_required
def mygroup_index(request):
    member = Member.objects.all().filter(user_id=request.user.id)
    return render(request,'main_app/mygroup.html',{
        'member': member
    })
class GroupUpdate(LoginRequiredMixin, UpdateView):
    model = Group
    fields = ['name']

class GroupDelete(LoginRequiredMixin, DeleteView):
    model = Group
    def get_success_url(self):
        group = self.get_object()
        interest_id = group.interest_id
        success_url = reverse_lazy('group_list', kwargs={
                                   'interest_id': interest_id})
        return success_url

@login_required
def topic_create(request, group_id):
    form = TopicForm(request.POST)
    if form.is_valid():
        new_topic = form.save(commit=False)
        new_topic.group_id = group_id
        new_topic.owner = request.user
        new_topic.save()
    return redirect('group_detail', group_id=group_id)

class TopicUpdate(LoginRequiredMixin, UpdateView):
    model = Topic
    fields = ['name']

class TopicDelete(LoginRequiredMixin, DeleteView):
    model = Topic
    group_id = model.group_id

    def get_success_url(self):
        topic = self.get_object()
        group_id = topic.group_id
        success_url = reverse_lazy('group_detail', kwargs={
                                   'group_id': group_id})
        return success_url

@login_required
def topic_detail(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic_form = TopicForm()
    post_form = PostForm()
    group = topic.group
    user_id = request.user.id
    likes = Like.objects.all().filter(user_id = user_id)
    
    def user_like_post(self):
        return self.like_set.get(user_id = self.user.id)

    return render(request, 'main_app/topic_detail.html', {
        'group': group,
        'topic_form': topic_form,
        'post_form': post_form,
        'topic': topic,
        'user_id': user_id,
        'likes': likes
    })

@login_required
def post_create(request, group_id, topic_id):
    form = PostForm(request.POST)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.topic_id = topic_id
        new_post.user_id = request.user.id
        photo_file = request.FILES.get('photo-file', None)
        if photo_file:
            s3 = boto3.client('s3')
            # need a unique "key" for S3 / needs image file extension too
            key = uuid.uuid4().hex[:6] + \
                photo_file.name[photo_file.name.rfind('.'):]
            # just in case something goes wrong
            try:
                bucket = os.environ['S3_BUCKET']
                s3.upload_fileobj(photo_file, bucket, key)
                # build the full url string
                url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                # we can assign to cat_id or cat (if you have a cat object)
                new_post.image_url = url
            except Exception as e:
                print('An error occurred uploading file to S3')
                print(e)
        new_post.save()
    return redirect('topic_detail', topic_id)


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['content']

    def get_success_url(self):
        post = self.get_object()
        topic_id =post.topic_id
        group_id = post.topic.group_id
        success_url = reverse_lazy('topic_detail', kwargs={
                                   'topic_id': topic_id})
        return success_url

class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        post = self.get_object()
        topic_id =post.topic_id
        group_id = post.topic.group_id
        success_url = reverse_lazy('topic_detail', kwargs={
                                   'topic_id': topic_id})
        return success_url

@login_required
def add_member_to_group(request,interest_id,group_id):
    Member.objects.create(user_id=request.user.id, group_id=group_id, interest_id=interest_id)
    return redirect('group_detail', group_id=group_id)

@login_required
def create_like(request, group_id, post_id):
    post = Post.objects.get(id=post_id)
    topic_id = post.topic_id
    like = post.like_set.filter(user=request.user)
    if len(like) == 0:
        Like.objects.create(post_id=post_id, user_id= request.user.id )
    return redirect('topic_detail', topic_id=topic_id)

def signup(request):
    error_message = ''
    form = UserCreationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('interest_list')
        else:
            error_message = 'Invalid sign up - try again'
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/main_app/group_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}


<div class="col-start-2 col-span-8 flex items-center justify-center mb-40 mr-20">
    <div class="col-start-2 col-span-3 mr-5 max-w-xl">

    <h1 class="ml-10 mt-10  text-7xl font-bold  capitalize leading-loose ">Are you sure you want to delete<span class="text-7xl   underline italic leading-loose font-bold text-center text-center m-10 ml-0 mt-4 text-transparent text-4xl bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400"> {{ object.name }}?</span></h1>
    
</div>
<div class="col-start-6 col-span-3 flex flex-col justify-center">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <div class="">
            <input type="submit" value="Delete" class="btn btn-lg btn-error btn-wide m-6">
            <a class="btn btn-lg btn-wide btn-warning m-6" href="{% url 'group_list' object.id %}">Cancel</a>
        </div>
    </form>
</div>
</div>


{% endblock %}

main_app/templates/main_app/group_confrim_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Group</h1>

<h4>Are you sure you want to delete {{ object.name }} ? </h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a href="{% url 'interest_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/group_form.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}
<div class="col-start-2 col-span-8 flex items-center justify-center mb-40 mr-20">
    <div class="col-start-2 col-span-3 mr-5 max-w-xl">
    {% if object%}
        <h1  class="ml-10 leading-none mb-10  text-7xl font-bold leading-loose">Edit <span class="text-7xl underline italic leading-loose font-bold text-center text-center m-10 ml-0 text-transparent text-4xl bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">{{ object.name }}</span></h1>
    {% endif %}
    </div>
    <div class="col-start-6 col-span-2 flex flex-col mb-20">
        <form class=" text-xl  action="" method="POST">
            {% csrf_token %}
            <table>
            {{form|crispy}}
            </table>
            <input class="btn btn-lg btn-wide btn-outline btn-success text-black mt-5" type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock%}

main_app/templates/main_app/group_new.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content%}
<div class="col-start-2 col-span-8 flex items-center justify-center mb-40 mr-20">
    <div class="col-start-2 col-span-3 mr-5 max-w-2xl">
        <h1 class="text-7xl underline italic leading-loose font-bold text-center text-center m-10 text-transparent text-4xl bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Create a New Group</h1>
    </div>
    <div class="col-start-6 col-span-2 mt-10 p-10">
        <form action="{% url 'group_create'  interest_id%}" enctype="multipart/form-data" method="POST">
            {%csrf_token%}
            {{group_form|crispy}}
            <label class="capitalize m-3" for="">add image</label>
            <input type="file"  name="photo-file" class=" mt-5 block w-full text-sm text-slate-500
            file:mr-4 file:py-2 file:px-4
            file:rounded-full file:border-0
            file:text-sm file:font-semibold
            file:bg-green-50 file:text-green-700
            hover:file:bg-green-100"
            />
            <input type="submit" value="Submit" class="btn btn-wide btn-outline btn-success mt-5">
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/post_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content %}

<div class="col-start-2 col-span-8 flex items-center justify-center mb-40 mr-20">
    <div class="col-start-2 col-span-3 mr-5 max-w-xl">
        <h1 class="ml-10 mt-10 text-7xl font-bold  capitalize leading-loose">Are you sure you want to delete this post?</h1>
    </div>
    <div class="col-start-4 col-span-3 mt-10 flex flex-col justify-center">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input class=" btn btn-lg btn-error btn-wide m-6" type="submit" value="Delete" class="btn">
            <a class="btn btn-lg btn-wide btn-warning m-6" href="{% url 'group_detail' post.topic.group_id %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/topic_detail.html
{% extends 'base.html'%}
{%load check_likes%}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
{% block content%}
<div class="hidden xl:block xl:col-span-2 mt-5 ml-5">
    <div class="w-[355px] flex flex-col gap-5 sticky top-[8rem] bottom-0 left-3">
        <div class="row-span-2 min-w-fit">
            <div class="w-full p-4 text-center bg-white border border-gray-200 rounded-lg shadow sm:p-8  dark:bg-gray-800 dark:border-gray-700">
                    <h5 class="mb-2 text-5xl font-bold text-gray-900 capitalize dark:text-white"><a href="{% url 'group_detail' group.id %}"><span class="text-3xl">Current Group:</span><br>{{ group.name }}</a></h5>
                    <a class="btn btn-wide btn-sm  m-3 btn-warning" href="{% url 'group_update' group.id %}">Edit</a>
                    <a class="btn btn-wide btn-sm btn-error" href="{% url 'group_delete' group.id %}">Delete</a> 
            </div>
        </div>
        <div class="mt-3 ml-5">
            <h1 class="text-3xl font-bold">Code of Conduct</h1>
            <ol class="mt-5 text-lg">
                <li class="flex items-center">
                    <svg class="w-3.5 h-3.5 mr-2 text-green-500 dark:text-green-400 flex-shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                        </svg>
                        Be civil and respectful
                </li>
                <li class="flex items-center">
                    <svg class="w-3.5 h-3.5 mr-2 text-green-500 dark:text-green-400 flex-shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                        </svg>
                        Posts must be related to the interest
                </li>
                <li class="flex items-center">
                    <svg class="w-3.5 h-3.5 mr-2 text-green-500 dark:text-green-400 flex-shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                        </svg>
                        No advertising, sponsored content or marketing
                </li>
                <li class="flex items-center">
                    <svg class="w-3.5 h-3.5 mr-2 text-green-500 dark:text-green-400 flex-shrink-0" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                        </svg>
                        No hate speech
                </li> 
            </ol>
        </div>
    </div>
</div>
<div class="col-start-2 col-span-8 xl:col-start-4 xl:col-span-6 mt-10">
    <div class="card mt-10">
        <h5 class="mb-5 text-5xl font-bold text-gray-900 capitalize dark:text-white">{{ topic.name }}</h5>
    </div>
    <div class="max-w-4xl">
        <form action="{% url 'post_create' group.id topic.id %}" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="w-full mb-4 border border-gray-200 rounded-lg  bg-gray-50 dark:bg-gray-700 dark:border-gray-600">
                <div class="px-4 py-2 bg-white rounded-t-lg dark:bg-gray-800">
                    <label for="comment" class="sr-only">Your comment</label>
                    <textarea id="comment" name="content" rows="3" class="w-full outline-none  px-0 text-sm text-gray-900 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400" placeholder="Write a comment..." required></textarea>
                </div>
                <div class="flex items-center justify-between px-3 py-2 border-t dark:border-gray-600">
                    <div class="flex pl-0 space-x-1 sm:pl-2 p-2">
                        <input type="file"  name="photo-file" class="  block w-full text-sm text-slate-500
                        file:mr-4 file:py-2 file:px-4
                        file:rounded-full file:border-0
                        file:text-sm file:font-semibold
                        file:bg-green-50 file:text-green-700
                        hover:file:bg-green-100"
                        />
                    </div>
                    <button type="submit" class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">
                        Post comment
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div>
        <p class="card-title uppercase mb-10 mt-10">Browse Posts:</p>
        {% for post in topic.post_set.all %}
            <div class="max-w-4xl h-120 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 relative mb-4">
                {%if post.user_id == user_id%}
                <div class=" absolute right-0 top-0 z-40">
                    <div class="dropdown dropdown-end ">
                        <label tabindex="0" class="btn bg-white border-0  dark:bg-gray-800 m-1">
                            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
                                <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
                            </svg>
                        </label>
                        <ul tabindex="0" class="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
                            <li>
                                <a href="{% url 'post_update' post.id %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Edit</a>
                            </li>
                            <li>
                                <a href="{% url 'post_delete' post.id %}" class="block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete</a>
                            </li>
                        </ul>
                    </div>
                </div>
                {%endif%}
                <div class="p-5 flex flex-col relative ">
                    <div class="flex p-2 items-center absolute top-0 left-0">
                        <div class="w-10 h-10 text-2xl rounded-full bg-black flex justify-center items-center">△</div>
                        <div class="ml-2"><p>{{post.user}}</p></div>
                    </div>
                    <p class="mb-3 ml-4 mt-6 relative top-3 font-normal text-gray-700 dark:text-gray-400">{{post.content}}</p>  
                </div>
                <img class="rounded-t-lg  " src="{{post.image_url}}" alt="" />
                <div class="h-10 flex items-center p-4">
                    <div>
                        <form  action="{% url 'create_like' group.id post.id%}" method="POST">
                            {%csrf_token%}
                            <button type="submit">
                                {% if likes|check_like_exists:post %}
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="red" viewBox="0 0 21 19">
                                    <path stroke="red"  d="M11 4C5.5-1.5-1.5 5.5 4 11l7 7 7-7c5.458-5.458-1.542-12.458-7-7Z"/></svg>
                                    {%else%}
                                    <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 19">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 4C5.5-1.5-1.5 5.5 4 11l7 7 7-7c5.458-5.458-1.542-12.458-7-7Z"/></svg>
                                    {%endif%}
                                
                            </button>
                        </form>
                    </div>
                    <p class="p-4">{{post.like_set.count}}</p>
                </div>
            </div>
        {%endfor%}
    </div>
</div>
{% endblock %}